from enigmatic import Enigma
from rich.console import Console
import rich.traceback

rich.traceback.install(show_locals=True)

# console
console = Console(legacy_windows=False, color_system="truecolor", style="Black on bright_white")
console.size = (200, 50)

enigma = Enigma(['ukw_caesar', 'beta', 'V', 'VI', 'VIII'])
enigma.plugboard.cables = "AE BF CM DQ HU JN LX PR SZ VW"
enigma.wheel_positions = "*SCHL"
enigma.ring_positions = "*AAEL"

cypher_text = """TAWZZYNZGGMICVLSADLQFDFKHDGZLSEEMDFFBQLYISEIWKDONDWJWETKZOWWYLTYII
OWSMCFTGNLKOZCAAWHBHFJDRWLDHFHEWUBPWVDEZFPBOCVKECVFXWZGSVBDPHLTVOJCFLSQNSODYFMBQFQU
LTHDISGOQURABEHHIBNXNAAKLEJMXQHJWXAVDLVTPTSTDCPWPYXCUVWAFJTTSFUSPTHOSTHXADWRQWZJCTU
KWCWHYFYQTRTPKPPJGPMDZQDAXAIZLWCADYZUTLXJJUDQGMFWZRWZXBQRHNCRUFUZZ.LALDHHOIBWYPKTSR
NQUHMUPTFWUHWBIKMASACVPRELBRRMRKLZWLVSFGUQFFXTAVQIHXDXRKQVGARLMZDBMDGRYNWIYSHWCNHIW
XYFBFGXXQNPTSEROCVYTOJTKKLQRALUDQMUFAKRHKOJCMWPSZHNAVVSEWFFPGRJTVNOLSGRERKXSCYWBOQT
PXOXJLQXSPYTMEOXOURSHIBYBNWQEFPTGGMCVXNGCDFQIYLCMPDLWOOAALODSWCDAWOZOMBGDZOQKZWQKFR
MRWCHGWFUERWPJAQFDRBVOAEYYAIYNPCLJDXOCBAZOHQOKVUFGLQNXQYDUZJIFXRVJDQ.OOOGXIGNONPEQL
KQBTVJ.DANIXQ.FDYXRDTQTFP.ZEHEOMXPPPFGGLTVFODHBSQPAQMDDWXMMGAJZVURSIYGAAXDZDV""".replace(".", "")

output_text = enigma.write(cypher_text)
console.print(output_text)
