from enigmatic.enigma import Enigma
from pyscript import document

enigma = Enigma.assemble(wheel_specs=["ukw_caesar", "beta", "V", "VI", "VIII"])
enigma.plug_board.add_cables("AE BF CM DQ HU JN LX PR SZ VW")
enigma.wheel_positions = "*SCHL"
enigma.ring_positions = "*AAEL"

cypher_text = """TAWZZYNZGGMICVLSADLQFDFKHDGZLSEEMDFFBQLYISEIWKDONDWJWETKZOWWYLTYII
OWSMCFTGNLKOZCAAWHBHFJDRWLDHFHEWUBPWVDEZFPBOCVKECVFXWZGSVBDPHLTVOJCFLSQNSODYFMBQFQU
LTHDISGOQURABEHHIBNXNAAKLEJMXQHJWXAVDLVTPTSTDCPWPYXCUVWAFJTTSFUSPTHOSTHXADWRQWZJCTU
KWCWHYFYQTRTPKPPJGPMDZQDAXAIZLWCADYZUTLXJJUDQGMFWZRWZXBQRHNCRUFUZZ.LALDHHOIBWYPKTSR
NQUHMUPTFWUHWBIKMASACVPRELBRRMRKLZWLVSFGUQFFXTAVQIHXDXRKQVGARLMZDBMDGRYNWIYSHWCNHIW
XYFBFGXXQNPTSEROCVYTOJTKKLQRALUDQMUFAKRHKOJCMWPSZHNAVVSEWFFPGRJTVNOLSGRERKXSCYWBOQT
PXOXJLQXSPYTMEOXOURSHIBYBNWQEFPTGGMCVXNGCDFQIYLCMPDLWOOAALODSWCDAWOZOMBGDZOQKZWQKFR
MRWCHGWFUERWPJAQFDRBVOAEYYAIYNPCLJDXOCBAZOHQOKVUFGLQNXQYDUZJIFXRVJDQ.OOOGXIGNONPEQL
KQBTVJ.DANIXQ.FDYXRDTQTFP.ZEHEOMXPPPFGGLTVFODHBSQPAQMDDWXMMGAJZVURSIYGAAXDZDV""".replace(".", "")

c_el = document.querySelector("#cyper")
c_el.innerHTML = cypher_text

output_text = enigma.write(cypher_text)
c_el = document.querySelector("#decode")
c_el.innerHTML = output_text